FROM python:3.9-alpine as builder

COPY ["datapath.py", "/opt/"]
COPY requirements.txt requirements-dp.txt

RUN pip3 install --no-cache-dir -r requirements-dp.txt

FROM builder

CMD ["python3", "/opt/datapath.py"]