FROM python:3.9-alpine as builder

COPY ["app/truth_seeker.py", "/opt/"]
COPY ["dynaconfig.py", "/opt/"]
COPY ["news_db.py", "/opt/"]
COPY requirements-ts.txt requirements-ts.txt

RUN pip3 install --no-cache-dir -r requirements-ts.txt

FROM builder

CMD ["python3", "/opt/truth_seeker.py"]