FROM python:3.9-alpine as builder

COPY ["truth_seeker.py", "/opt/"]
COPY ["datapath.py", "/opt/"]
COPY ["news_db.py", "/opt/"]
COPY ["dynaconfig.py", "/opt/"]
COPY requirements-ts.txt requirements-ts.txt

RUN apk --no-cache --update-cache add libc-dev build-base
RUN pip3 install -U pip

RUN pip3 install --no-cache-dir -r requirements-ts.txt

FROM builder

CMD ["python3.9", "/opt/truth_seeker.py"]