FROM python:3.9-alpine as builder

COPY ["db.py", "/opt/"]
COPY requirements.txt requirements-db.txt

RUN pip3 install --no-cache-dir -r requirements-db.txt

FROM builder

CMD ["python3", "/opt/db.py"]