FROM python:3.9-alpine as builder

COPY ["app/", "/opt/app/"]
COPY ["news_db.py", "/opt/"]
COPY ["dynaconfig.py", "/opt/"]
COPY requirements-db.txt requirements-db.txt

RUN pip3 install --no-cache-dir -r requirements-db.txt

FROM builder

CMD ["python3", "/opt/news_db.py"]