version: '3'

services:
  news_db:
    container_name: news_db
    image: h0d0user/news_db:v0.0.44
    restart: always
    network_mode: host
    volumes:
      - "shared-volume:/mnt/"
      - ".secrets.toml:/opt/.secrets.toml"

  truth_seeker:
    container_name: truth_seeker
    image: h0d0user/truth_seeker:v0.0.44
    restart: always
    network_mode: host
    depends_on:
      - "news_db"
    volumes:
      - "shared-volume:/mnt/"
      - ".secrets.toml:/opt/.secrets.toml"

  datapath:
    container_name: datapath
    image: h0d0user/datapath:v0.0.44
    restart: always
    network_mode: host
    depends_on:
      - "news_db"
    volumes:
      - "shared-volume:/mnt/"
      - ".secrets.toml:/opt/.secrets.toml"

volumes:
  shared-volume:
