version: '3'

services:
#  news_db:
#    container_name: news_db
#    image: h0d0user/news_db:latest
#    pull_policy: always
#    restart: always
#    network_mode: host
#    volumes:
#      - "shared-volume:/mnt/"
#      - "./settings.toml:/opt/settings.toml"

  epistolary:
    container_name: epistolary
    image: h0d0user/epistolary:latest
    pull_policy: always
    restart: always
#    network_mode: host
    networks:
      - etl
    hostname: epistolary
    ports:
      - "8888:8888"
#    depends_on:
#      - "news_db"
    volumes:
#      - "shared-volume:/mnt/"
      - "./settings.toml:/opt/settings.toml"

  datapath:
    container_name: datapath
    image: h0d0user/datapath:latest
    pull_policy: always
    restart: always
#    network_mode: host
    networks:
      - etl
    depends_on:
      - "epistolary"
    volumes:
      - "./settings.toml:/opt/settings.toml"

volumes:
  shared-volume:

networks:
  etl: